config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

resources :reviews do
  resources :comments
  resource :bookmark
end

resources :users

resource :session

resource :account

get "about", to: "pages#about"
get "terms", to: "pages#terms"

root "pages#home"

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

#check if logged in
before_action :check_login, except: [:index, :show]

  def index
    # this is our list page for our reviews
    @price = params[:price]
    @cuisine = params[:cuisine]
    @location = params[:location]

    #start with all the Reviews
    @reviews = Review.all

    #filtering by prices
    if @price.present?
      @reviews = @reviews.where(price: @price)
    end

    #filter by Cuisine
    if @cuisine.present?
      @reviews = @reviews.where(cuisine: @cuisine)
    end

    #search near the location
    if @location.present?
      @reviews = @reviews.near(@location)
    end

  end

  def new
    @review = Review.new
  end


  def create
    #take the info from the for and add it to the model
    @review = Review.new(form_params)

    # and then associate it with a user
    @review.user = @current_user

    #we want to check if the model can be saved
    #if it is, we're go the home page again
    #if it isn't, show the new form_for

    #save this to the database
    if @review.save
    #redirect back to the homepage
      flash[:success] = "Your review was posted!"
      redirect_to root_path
    else
      #show the view for new.html.erb
      render "new"
    end

  end

  def show
    #individual review page
    @review = Review.find(params[:id])
  end

  def destroy
    #find the individiual review
    @review = Review.find(params[:id])

    #destroy if they have access
    if @review.user == @current_user
      @review.destroy
    end

    #redirect to the homepage
    redirect_to root_path
  end

  def edit
    #find the individual review (to edit)
    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to root_path
      #can't access the edit page if more than an hour ago
    elsif @review.created_at < 1.hour.ago
      redirect_to review_path(@review)
    end
  end

  def update
      #find the individual review
      @review = Review.find(params[:id])

      if @review.user != @current_user
        redirect_to root_path
      else
        #update with the new form info
        if @review.update(form_params)
          flash[:success] = "Your review was updated!"
        #redirect somewhere new
        redirect_to review_path(@review)
        else
          render "edit"
        end
      end
  end

  def form_params
    params.require(:review).permit(:title, :restaurant, :address, :photo, :body, :score, :ambiance, :cuisine, :price)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :title %>
  <%= f.input :restaurant %>
  <%= f.input :address %>
  <%= f.input :photo %>
  <%= f.input :body %>
  <%= f.input :cuisine %>
  <%= f.input :price %>
  <%= f.input :score %>
  <%= f.input :ambiance %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/edit.html.erb
<h3>Edit restaurant review!</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
  <%= active_link_to "All restaurants", root_path, active: {price: nil, location: nil, cuisine: nil} %>
  <div>
    <%= active_link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location), active: {price: 1} %>
    <%= active_link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location), active: {price: 2} %>
    <%= active_link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location), active: {price: 3} %>
  </div>

  <div >
    <%= active_link_to "Indian", root_path(cuisine: "Indian", price: @price, location: @location), active: {cuisine: "Indian"} %>
    <%= active_link_to "Mexican", root_path(cuisine: "Mexican", price: @price, location: @location), active: {cuisine: "Mexican"} %>
    <%= active_link_to "American", root_path(cuisine: "American", price: @price, location: @location), active: {cuisine: "American"} %>
  </div>

  <form action="/" >
    <input type="text" name="location" placeholder="Search location..." value=" <%= @location %> ">
    <input type="hidden" name="price" value="<%= @price %>">
    <input type="hidden" name="cuisine" value="<%= @cuisine %>">
  </form>
</nav>

<% @reviews.each do |review| %>
  <div class="review">
  <%= link_to review_path(review) do %>

  <% if review.photo.url %>
    <%= image_tag review.photo.thumb.url %>
 <% end %>

  <h2><%= review.title %></h2>
  <p>
    <%= review.cuisine %> - <%= pluralize review.comments.count, "comment" %>
  </p>
  <% end %>

  </div>
<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3>Add your new restaurant review!</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>


<h1> <%= @review.title %> </h1>
<h2> <%= @review.restaurant %> </h2>

<% if @review.photo.present? %>
<%= image_tag @review.photo.url, alt: 'photo of the reviewers dish' %>
<% end %>

<% if is_logged_in? %>
<p>

  <% if @review.bookmarks.where(user: @current_user).any? %>
  <%= link_to "Unbookmark", review_bookmark_path(@review), method: :delete %>
  <% else %>
    <%= link_to "Bookmark", review_bookmark_path(@review), method: :post %>
  <% end %>
</p>
<% end %>

<h3>Bookmarked by...</h3>
<ul>
  <% @review.bookmarks.each do |bookmark| %>

  <li> <%= bookmark.user.username %> </li>
  <% end %>
</ul>


<div class="score">
<%= @review.score %>/10
</div>

<div class="user">
  Posted by
    <% if @review.user.present? %>
    <%= link_to user_path(@review.user) do %>
    <p class="user-profile">
      <% if @review.user.avatar.present? %>
          <%= image_tag @review.user.avatar.url, class: "avatar" %>
      <% end %>
      <%= @review.user.username %>
    </p>
    <% end %>
    <% else %>
    anonymous
    <% end %>
</div>

<% if @review.ambiance.present? %>
  <div class="ambiance">
    Ambiance: <%= @review.ambiance %>
  </div>
<% end %>

<% if @review.price.present? %>
  <div class="price">
    Price: <%= @review.price %>
  </div>
<% end %>

<% if @review.cuisine.present? %>
  <div class="cuisine">
    Cuisine: <%= @review.cuisine %>
  </div>
<% end %>

<div class="body">
  <%= simple_format @review.body %>
</div>

<% if @review.user == @current_user %>
<div class="actions">
  <% if @review.created_at > 1.hour.ago %>
  <%= link_to "Edit this review", edit_review_path(@review) %>
  <% end %>
  <%= link_to "Delete this review", review_path(@review), method: :delete, data: {confirm: "Are you sure??"} %>

</div>
<% end %>

<h3>Comments</h3>
<% @review.comments.order("created_at desc").each do |comment| %>
<div class="comment">
  <%= simple_format comment.body %>

  <p class="posted">Posted by
    <% if comment.user.present? %>
    <%= link_to comment.user.username, user_path(comment.user)%>
    <% else %>
    anonymous
    <% end %>
  </p>
  <p class="posted">Posted <%= time_ago_in_words comment.created_at %> ago</p>
</div>
<% end %>

<h3>Add a comment</h3>

<%= simple_form_for [@review, Comment.new] do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, "Add comment" %>
<% end %>